packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - workerd

catalog:
  valibot: ^1.2.0
